In [1]:
import torch

In [2]:
# torch.tensor([2,3])
# torch.tensor([[2,3],[4,5]])
# torch.tensor([[2,3],[4,5]],dtype = torch.float32)
# torch.tensor([[2,3],[4,5]],dtype = torch.double)
# torch.tensor([[2,3],[4,5]],dtype = torch.float32)
# torch.tensor([[2,3],[4,5]],dtype = torch.float32,requires_grad = True)
# torch.tensor([[2,3],[4,5]],requires_grad = True)
torch.tensor([[2,3],[4,5]], device = torch.device('cuda:0'))

tensor([[2, 3],
        [4, 5]], device='cuda:0')

In [81]:
tensor = torch.tensor([[[2,3],[4,5],[6,7],[8,9]]],
                     dtype = torch.float32,
                      requires_grad = True
                     )
# tensor.dtype
# tensor.size()
# tensor.shape
# tensor.ndim
# tensor[0,0,0]
# type(tensor[0,0,0])
# tensor[0,3,1].item()

In [86]:
# tensor = torch.zeros([2,3,2])
# tensor

# tensor = torch.zeros([2,3,2])
# tensor

# tensor = torch.ones([2,3,2])
# tensor

tensor = torch.zeros_like(tensor)

tensor = torch.full_like(tensor, 19)
tensor

tensor([[[19., 19.],
         [19., 19.],
         [19., 19.]],

        [[19., 19.],
         [19., 19.],
         [19., 19.]]])

In [93]:
# CPU and GPU
# print(torch.cpu.is_available())
# print(torch.cuda.is_available())

In [95]:
tensor = torch.tensor([1.,2.,3.], requires_grad = True)

In [99]:
# tensor = tensor.cpu()
# tensor = tensor.to('cpu')
tensor = tensor.cuda()
# tensor = tensor.to('cuda')

tensor

tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>)

In [100]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor = tensor.to(device)

In [101]:
tensor.device

device(type='cuda', index=0)

In [102]:
tensor1 = torch.tensor([1.,2.,3.]).to('cpu')
tensor1

tensor([1., 2., 3.])

In [106]:
# new_tensor = tensor + tensor1
new_tensor = tensor + tensor1.to(device)
new_tensor

tensor([2., 4., 6.], device='cuda:0', grad_fn=<AddBackward0>)

In [21]:
random_tensor = torch.rand(2,2)
random_tensor_2 = torch.rand([2,2])
random_tensor.log2(), random_tensor_2.log2_()

(tensor([[-1.2057, -0.7985],
         [-3.0556, -0.5208]]),
 tensor([[-0.8999, -0.7277],
         [-2.4411, -1.1269]]))

In [24]:
flat_tensor = torch.rand(784)
reshapped_tensor = flat_tensor.reshape(1,28,28)
flat_tensor.dim(), reshapped_tensor.dim()

(1, 3)

In [25]:
hwc_tensor = torch.rand(640,480,3)
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])